#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-lxml
Version  : 4.9.1
Release  : 96
URL      : https://files.pythonhosted.org/packages/70/bb/7a2c7b4f8f434aa1ee801704bf08f1e53d7b5feba3d5313ab17003477808/lxml-4.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/70/bb/7a2c7b4f8f434aa1ee801704bf08f1e53d7b5feba3d5313ab17003477808/lxml-4.9.1.tar.gz
Summary  : Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: pypi-lxml-filemap = %{version}-%{release}
Requires: pypi-lxml-lib = %{version}-%{release}
Requires: pypi-lxml-license = %{version}-%{release}
Requires: pypi-lxml-python = %{version}-%{release}
Requires: pypi-lxml-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : libxml2-dev
BuildRequires : libxslt-dev
BuildRequires : pypi(cython)
BuildRequires : zlib-dev

%description
What is lxml?
=============
lxml is the most feature-rich and easy-to-use library for processing XML and HTML in the Python language.
It's also very fast and memory friendly, just so you know.

%package filemap
Summary: filemap components for the pypi-lxml package.
Group: Default

%description filemap
filemap components for the pypi-lxml package.


%package lib
Summary: lib components for the pypi-lxml package.
Group: Libraries
Requires: pypi-lxml-license = %{version}-%{release}
Requires: pypi-lxml-filemap = %{version}-%{release}

%description lib
lib components for the pypi-lxml package.


%package license
Summary: license components for the pypi-lxml package.
Group: Default

%description license
license components for the pypi-lxml package.


%package python
Summary: python components for the pypi-lxml package.
Group: Default
Requires: pypi-lxml-python3 = %{version}-%{release}

%description python
python components for the pypi-lxml package.


%package python3
Summary: python3 components for the pypi-lxml package.
Group: Default
Requires: pypi-lxml-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(lxml)
Requires: pypi(cython)

%description python3
python3 components for the pypi-lxml package.


%prep
%setup -q -n lxml-4.9.1
cd %{_builddir}/lxml-4.9.1
pushd ..
cp -a lxml-4.9.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657036062
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build  %{?_smp_mflags}

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build  %{?_smp_mflags}

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-lxml
cp %{_builddir}/lxml-4.9.1/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-lxml/9952214ce0aca4410ff3c7711d8389893713fe3b
cp %{_builddir}/lxml-4.9.1/LICENSES.txt %{buildroot}/usr/share/package-licenses/pypi-lxml/495ceccaff92184d795e03cfc863c015dc3dced9
cp %{_builddir}/lxml-4.9.1/doc/licenses/GPL.txt %{buildroot}/usr/share/package-licenses/pypi-lxml/dfac199a7539a404407098a2541b9482279f690d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-lxml

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-lxml/495ceccaff92184d795e03cfc863c015dc3dced9
/usr/share/package-licenses/pypi-lxml/9952214ce0aca4410ff3c7711d8389893713fe3b
/usr/share/package-licenses/pypi-lxml/dfac199a7539a404407098a2541b9482279f690d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
